config/routes.rb
Crave::Application.routes.draw do 
  resources :user_vote_cities

  resources :foursquare_checkins

  resources :alpha_testers

  resources :following, :as => "user_followings", :controller => "user_followings"
  
  resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings" do
    resources :helpful, :as => "menu_item_rating_helpfuls", :controller => "menu_item_rating_helpfuls" do
      collection do
        get 'count'
      end
    end
  end

  resources :helpful, :as => "menu_item_rating_helpfuls", :controller => "menu_item_rating_helpfuls"

  resources :items, :as => "menu_items", :controller => "menu_items" do
    resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings" do
      collection do
        get 'avg_rating'
      end 
    end

    member do
      get 'show_reviews'
      post 'upload_photo'
    end
    collection do
      get 'search', 'nearby', 'show_menu_items_nearby' ,'show_menu_items_of_place' , 'nearby_loading', 'food_by_foursquare_venue'
    end
  end

  resources :places, :as => "restaurants", :controller => "restaurants" do
    resources :items, :as => "menu_items", :controller => "menu_items" do
      collection do
        get 'admin'
      end
    end
    collection do
      get 'search', 'show_restaurants_nearby'
    end
    member do
      get 'details'
    end
  end

  resources :users do
    member do
      get "saved", "following", "followers", "following_reviews"
    end

    collection do
      get "get_uid"
    end
    resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings"
  end
  
  resources :saved, :as => "user_saved_menu_items", :controller => "user_saved_menu_items" do 	
    collection do
      get "show_menu_items_saved", "is_saved"
    end
  end
  
  resources :restaurant_label_associations
  resources :restaurant_cuisine_associations
  resources :restaurant_labels
  resources :restaurant_cuisines  
  resources :menu_label_associations
  resources :menu_item_review_comments
  resources :menu_labels
  resources :menu_item_photos
  resources :menu_item_ingredients
  resources :ingredients
  resources :menu_item_prices
  resources :search
  resources :user_followings
  
  match '/activity', :to => 'users#following_reviews'
  match '/foodies', :to => 'users#following_reviews'
  match '/auth/:provider/callback', :to => 'sessions#create'  
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/nearby' => 'menu_items#nearby_loading', :as => :nearby

end

app/models/restaurant_cuisine_association.rb
class RestaurantCuisineAssociation < ActiveRecord::Base
end

app/controllers/restaurant_cuisine_associations_controller.rb
class RestaurantCuisineAssociationsController < ApplicationController
  # GET /restaurant_cuisine_associations
  # GET /restaurant_cuisine_associations.xml
  def index
    @restaurant_cuisine_associations = RestaurantCuisineAssociation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @restaurant_cuisine_associations }
    end
  end

  # GET /restaurant_cuisine_associations/1
  # GET /restaurant_cuisine_associations/1.xml
  def show
    @restaurant_cuisine_association = RestaurantCuisineAssociation.find(params[:id])

    respond_to do |format|
      format.html # _unused_show.html.haml
      format.xml  { render :xml => @restaurant_cuisine_association }
    end
  end

  # GET /restaurant_cuisine_associations/new
  # GET /restaurant_cuisine_associations/new.xml
  def new
    @restaurant_cuisine_association = RestaurantCuisineAssociation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @restaurant_cuisine_association }
    end
  end

  # GET /restaurant_cuisine_associations/1/edit
  def edit
    @restaurant_cuisine_association = RestaurantCuisineAssociation.find(params[:id])
  end

  # POST /restaurant_cuisine_associations
  # POST /restaurant_cuisine_associations.xml
  def create
    @restaurant_cuisine_association = RestaurantCuisineAssociation.new(params[:restaurant_cuisine_association])

    respond_to do |format|
      if @restaurant_cuisine_association.save
        format.html { redirect_to(@restaurant_cuisine_association, :notice => 'Restaurant cuisine association was successfully created.') }
        format.xml  { render :xml => @restaurant_cuisine_association, :status => :created, :location => @restaurant_cuisine_association }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @restaurant_cuisine_association.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /restaurant_cuisine_associations/1
  # PUT /restaurant_cuisine_associations/1.xml
  def update
    @restaurant_cuisine_association = RestaurantCuisineAssociation.find(params[:id])

    respond_to do |format|
      if @restaurant_cuisine_association.update_attributes(params[:restaurant_cuisine_association])
        format.html { redirect_to(@restaurant_cuisine_association, :notice => 'Restaurant cuisine association was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @restaurant_cuisine_association.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant_cuisine_associations/1
  # DELETE /restaurant_cuisine_associations/1.xml
  def destroy
    @restaurant_cuisine_association = RestaurantCuisineAssociation.find(params[:id])
    @restaurant_cuisine_association.destroy

    respond_to do |format|
      format.html { redirect_to(restaurant_cuisine_associations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/restaurant_cuisine_associations_helper.rb
module RestaurantCuisineAssociationsHelper
end

app/views/restaurant_cuisine_associations/_form.html.erb
<%= form_for(@restaurant_cuisine_association) do |f| %>
  <% if @restaurant_cuisine_association.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant_cuisine_association.errors.count, "error") %> prohibited this restaurant_cuisine_association from being saved:</h2>

      <ul>
      <% @restaurant_cuisine_association.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_id %><br />
    <%= f.text_field :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_cuisine_id %><br />
    <%= f.text_field :restaurant_cuisine_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurant_cuisine_associations/edit.html.erb
<h1>Editing restaurant_cuisine_association</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_cuisine_association %> |
<%= link_to 'Back', restaurant_cuisine_associations_path %>

app/views/restaurant_cuisine_associations/index.html.erb
<h1>Listing restaurant_cuisine_associations</h1>

<table>
  <tr>
    <th>Restaurant</th>
    <th>Restaurant cuisine</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @restaurant_cuisine_associations.each do |restaurant_cuisine_association| %>
  <tr>
    <td><%= restaurant_cuisine_association.restaurant_id %></td>
    <td><%= restaurant_cuisine_association.restaurant_cuisine_id %></td>
    <td><%= link_to 'Show', restaurant_cuisine_association %></td>
    <td><%= link_to 'Edit', edit_restaurant_cuisine_association_path(restaurant_cuisine_association) %></td>
    <td><%= link_to 'Destroy', restaurant_cuisine_association, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurant cuisine association', new_restaurant_cuisine_association_path %>

app/views/restaurant_cuisine_associations/new.html.erb
<h1>New restaurant_cuisine_association</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_cuisine_associations_path %>

app/views/restaurant_cuisine_associations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Restaurant:</b>
  <%= @restaurant_cuisine_association.restaurant_id %>
</p>

<p>
  <b>Restaurant cuisine:</b>
  <%= @restaurant_cuisine_association.restaurant_cuisine_id %>
</p>


<%= link_to 'Edit', edit_restaurant_cuisine_association_path(@restaurant_cuisine_association) %> |
<%= link_to 'Back', restaurant_cuisine_associations_path %>