config/routes.rb
Crave::Application.routes.draw do 
  resources :user_vote_cities

  resources :foursquare_checkins

  resources :alpha_testers

  resources :following, :as => "user_followings", :controller => "user_followings"
  
  resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings" do
    resources :helpful, :as => "menu_item_rating_helpfuls", :controller => "menu_item_rating_helpfuls" do
      collection do
        get 'count'
      end
    end
  end

  resources :helpful, :as => "menu_item_rating_helpfuls", :controller => "menu_item_rating_helpfuls"

  resources :items, :as => "menu_items", :controller => "menu_items" do
    resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings" do
      collection do
        get 'avg_rating'
      end 
    end

    member do
      get 'show_reviews'
      post 'upload_photo'
    end
    collection do
      get 'search', 'nearby', 'show_menu_items_nearby' ,'show_menu_items_of_place' , 'nearby_loading', 'food_by_foursquare_venue'
    end
  end

  resources :places, :as => "restaurants", :controller => "restaurants" do
    resources :items, :as => "menu_items", :controller => "menu_items" do
      collection do
        get 'admin'
      end
    end
    collection do
      get 'search', 'show_restaurants_nearby'
    end
    member do
      get 'details'
    end
  end

  resources :users do
    member do
      get "saved", "following", "followers", "following_reviews"
    end

    collection do
      get "get_uid"
    end
    resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings"
  end
  
  resources :saved, :as => "user_saved_menu_items", :controller => "user_saved_menu_items" do 	
    collection do
      get "show_menu_items_saved", "is_saved"
    end
  end
  
  resources :restaurant_label_associations
  resources :restaurant_cuisine_associations
  resources :restaurant_labels
  resources :restaurant_cuisines  
  resources :menu_label_associations
  resources :menu_item_review_comments
  resources :menu_labels
  resources :menu_item_photos
  resources :menu_item_ingredients
  resources :ingredients
  resources :menu_item_prices
  resources :search
  resources :user_followings
  
  match '/activity', :to => 'users#following_reviews'
  match '/foodies', :to => 'users#following_reviews'
  match '/auth/:provider/callback', :to => 'sessions#create'  
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/nearby' => 'menu_items#nearby_loading', :as => :nearby

end

app/models/menu_item_rating_helpful.rb
class MenuItemRatingHelpful < ActiveRecord::Base
  belongs_to  :menu_item_rating
  validates_uniqueness_of :menu_item_rating_id, :scope => :user_id
  validates_presence_of :menu_item_rating_id, :user_id
end

app/controllers/menu_item_rating_helpfuls_controller.rb
class MenuItemRatingHelpfulsController < ApplicationController
  before_filter :get_menu_item_rating, :check_auth_fb
  
  # GET /menu_item_rating_helpfuls
  # GET /menu_item_rating_helpfuls.xml
  def index
    if (@menu_item_rating)
      @menu_item_rating_helpfuls = @menu_item_rating.menu_item_rating_helpfuls.find(:all)
    else 
      @menu_item_rating_helpfuls = MenuItemRatingHelpful.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @menu_item_rating_helpfuls }
      format.json  { render :json => @menu_item_rating_helpfuls }
    end
  end

  # GET /menu_item_rating_helpfuls/1
  # GET /menu_item_rating_helpfuls/1.xml
  def show
    @menu_item_rating_helpful = MenuItemRatingHelpful.find(params[:id])

    respond_to do |format|
      format.html # _unused_show.html.haml
      format.xml  { render :xml => @menu_item_rating_helpful }
      format.json  { render :json => @menu_item_rating_helpful }
    end
  end

  # GET /menu_item_rating_helpfuls/new
  # GET /menu_item_rating_helpfuls/new.xml
  def new
    @menu_item_rating_helpful = MenuItemRatingHelpful.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @menu_item_rating_helpful }
      format.json  { render :json => @menu_item_rating_helpful }
    end
  end
  
  def count
    #FIXME - account for @menu_item_rating = null
    @menu_item_rating_helpfuls_count = @menu_item_rating.menu_item_rating_helpfuls.find(:all).count
    
    respond_to do |format|
      format.json  { render :json => @menu_item_rating_helpfuls_count }
    end
  end

  # GET /menu_item_rating_helpfuls/1/edit
  def edit
    @menu_item_rating_helpful = MenuItemRatingHelpful.find(params[:id])
  end

  # POST /menu_item_rating_helpfuls
  # POST /menu_item_rating_helpfuls.xml
  def create
    @menu_item_rating_helpful = MenuItemRatingHelpful.new(params[:menu_item_rating_helpful])

    Notifier.review_helpful(current_user,
      @menu_item_rating_helpful.menu_item_rating.user, 
      @menu_item_rating_helpful.menu_item_rating.menu_item).deliver

    respond_to do |format|
      if @menu_item_rating_helpful.save
        format.html { redirect_to(@menu_item_rating_helpful, :notice => 'Menu item rating helpful was successfully created.') }
        format.xml  { render :xml => @menu_item_rating_helpful, :status => :created, :location => @menu_item_rating_helpful }
        format.json  { render :json => @menu_item_rating_helpful, :status => :created, :location => @menu_item_rating_helpful }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @menu_item_rating_helpful.errors, :status => :unprocessable_entity }
        format.json  { render :json => @menu_item_rating_helpful.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /menu_item_rating_helpfuls/1
  # PUT /menu_item_rating_helpfuls/1.xml
  def update
    @menu_item_rating_helpful = MenuItemRatingHelpful.find(params[:id])

    respond_to do |format|
      if @menu_item_rating_helpful.update_attributes(params[:menu_item_rating_helpful])
        format.html { redirect_to(@menu_item_rating_helpful, :notice => 'Menu item rating helpful was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @menu_item_rating_helpful.errors, :status => :unprocessable_entity }
        format.json  { render :json => @menu_item_rating_helpful.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_item_rating_helpfuls/1
  # DELETE /menu_item_rating_helpfuls/1.xml
  def destroy
    # @menu_item_rating_helpful = MenuItemRatingHelpful.find(params[:id])
    # @menu_item_rating_helpful.destroy

    respond_to do |format|
      format.html { redirect_to(menu_item_rating_helpfuls_url) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end
  
  private
    def get_menu_item_rating
      @menu_item_rating = MenuItemRating.find(params[:menu_item_rating_id]) unless params[:menu_item_rating_id].blank?
    end
end

app/helpers/menu_item_rating_helpfuls_helper.rb
module MenuItemRatingHelpfulsHelper
end

app/views/menu_item_rating_helpfuls/_form.html.erb
<%= form_for(@menu_item_rating_helpful, :remote => true) do |f| %>
  <% if @menu_item_rating_helpful.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item_rating_helpful.errors.count, "error") %> prohibited this menu_item_rating_helpful from being saved:</h2>

      <ul>
      <% @menu_item_rating_helpful.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_item_rating_id %><br />
    <%= f.text_field :menu_item_rating_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_item_rating_helpfuls/edit.html.erb
<h1>Editing menu_item_rating_helpful</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_item_rating_helpful %> |
<%= link_to 'Back', menu_item_rating_helpfuls_path %>

app/views/menu_item_rating_helpfuls/index.html.erb
<h1>Listing menu_item_rating_helpfuls</h1>

<table>
  <tr>
    <th>Menu item rating</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menu_item_rating_helpfuls.each do |menu_item_rating_helpful| %>
  <tr>
    <td><%= menu_item_rating_helpful.menu_item_rating_id %></td>
    <td><%= menu_item_rating_helpful.user_id %></td>
    <td><%= link_to 'Show', menu_item_rating_helpful %></td>
    <td><%= link_to 'Edit', edit_menu_item_rating_helpful_path(menu_item_rating_helpful) %></td>
    <td><%= link_to 'Destroy', menu_item_rating_helpful, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu item rating helpful', new_menu_item_rating_helpful_path %>

app/views/menu_item_rating_helpfuls/new.html.erb
<h1>New menu_item_rating_helpful</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_item_rating_helpfuls_path %>

app/views/menu_item_rating_helpfuls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Menu item rating:</b>
  <%= @menu_item_rating_helpful.menu_item_rating_id %>
</p>

<p>
  <b>User:</b>
  <%= @menu_item_rating_helpful.user_id %>
</p>


<%= link_to 'Edit', edit_menu_item_rating_helpful_path(@menu_item_rating_helpful) %> |
<%= link_to 'Back', menu_item_rating_helpfuls_path %>