config/routes.rb
Crave::Application.routes.draw do 
  resources :user_vote_cities

  resources :foursquare_checkins

  resources :alpha_testers

  resources :following, :as => "user_followings", :controller => "user_followings"
  
  resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings" do
    resources :helpful, :as => "menu_item_rating_helpfuls", :controller => "menu_item_rating_helpfuls" do
      collection do
        get 'count'
      end
    end
  end

  resources :helpful, :as => "menu_item_rating_helpfuls", :controller => "menu_item_rating_helpfuls"

  resources :items, :as => "menu_items", :controller => "menu_items" do
    resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings" do
      collection do
        get 'avg_rating'
      end 
    end

    member do
      get 'show_reviews'
      post 'upload_photo'
    end
    collection do
      get 'search', 'nearby', 'show_menu_items_nearby' ,'show_menu_items_of_place' , 'nearby_loading', 'food_by_foursquare_venue'
    end
  end

  resources :places, :as => "restaurants", :controller => "restaurants" do
    resources :items, :as => "menu_items", :controller => "menu_items" do
      collection do
        get 'admin'
      end
    end
    collection do
      get 'search', 'show_restaurants_nearby'
    end
    member do
      get 'details'
    end
  end

  resources :users do
    member do
      get "saved", "following", "followers", "following_reviews"
    end

    collection do
      get "get_uid"
    end
    resources :ratings, :as => "menu_item_ratings", :controller => "menu_item_ratings"
  end
  
  resources :saved, :as => "user_saved_menu_items", :controller => "user_saved_menu_items" do 	
    collection do
      get "show_menu_items_saved", "is_saved"
    end
  end
  
  resources :restaurant_label_associations
  resources :restaurant_cuisine_associations
  resources :restaurant_labels
  resources :restaurant_cuisines  
  resources :menu_label_associations
  resources :menu_item_review_comments
  resources :menu_labels
  resources :menu_item_photos
  resources :menu_item_ingredients
  resources :ingredients
  resources :menu_item_prices
  resources :search
  resources :user_followings
  
  match '/activity', :to => 'users#following_reviews'
  match '/foodies', :to => 'users#following_reviews'
  match '/auth/:provider/callback', :to => 'sessions#create'  
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/nearby' => 'menu_items#nearby_loading', :as => :nearby

end

app/models/menu_item_ingredient.rb
class MenuItemIngredient < ActiveRecord::Base
end

app/controllers/menu_item_ingredients_controller.rb
class MenuItemIngredientsController < ApplicationController
  # GET /menu_item_ingredients
  # GET /menu_item_ingredients.xml
  def index
    @menu_item_ingredients = MenuItemIngredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @menu_item_ingredients }
    end
  end

  # GET /menu_item_ingredients/1
  # GET /menu_item_ingredients/1.xml
  def show
    @menu_item_ingredient = MenuItemIngredient.find(params[:id])

    respond_to do |format|
      format.html # _unused_show.html.haml
      format.xml  { render :xml => @menu_item_ingredient }
    end
  end

  # GET /menu_item_ingredients/new
  # GET /menu_item_ingredients/new.xml
  def new
    @menu_item_ingredient = MenuItemIngredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @menu_item_ingredient }
    end
  end

  # GET /menu_item_ingredients/1/edit
  def edit
    @menu_item_ingredient = MenuItemIngredient.find(params[:id])
  end

  # POST /menu_item_ingredients
  # POST /menu_item_ingredients.xml
  def create
    @menu_item_ingredient = MenuItemIngredient.new(params[:menu_item_ingredient])

    respond_to do |format|
      if @menu_item_ingredient.save
        format.html { redirect_to(@menu_item_ingredient, :notice => 'Menu item ingredient was successfully created.') }
        format.xml  { render :xml => @menu_item_ingredient, :status => :created, :location => @menu_item_ingredient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @menu_item_ingredient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /menu_item_ingredients/1
  # PUT /menu_item_ingredients/1.xml
  def update
    @menu_item_ingredient = MenuItemIngredient.find(params[:id])

    respond_to do |format|
      if @menu_item_ingredient.update_attributes(params[:menu_item_ingredient])
        format.html { redirect_to(@menu_item_ingredient, :notice => 'Menu item ingredient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @menu_item_ingredient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_item_ingredients/1
  # DELETE /menu_item_ingredients/1.xml
  def destroy
    @menu_item_ingredient = MenuItemIngredient.find(params[:id])
    @menu_item_ingredient.destroy

    respond_to do |format|
      format.html { redirect_to(menu_item_ingredients_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/menu_item_ingredients_helper.rb
module MenuItemIngredientsHelper
end

app/views/menu_item_ingredients/_form.html.erb
<%= form_for(@menu_item_ingredient) do |f| %>
  <% if @menu_item_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item_ingredient.errors.count, "error") %> prohibited this menu_item_ingredient from being saved:</h2>

      <ul>
      <% @menu_item_ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_item_id %><br />
    <%= f.text_field :menu_item_id %>
  </div>
  <div class="field">
    <%= f.label :ingredient_id %><br />
    <%= f.text_field :ingredient_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_item_ingredients/edit.html.erb
<h1>Editing menu_item_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_item_ingredient %> |
<%= link_to 'Back', menu_item_ingredients_path %>

app/views/menu_item_ingredients/index.html.erb
<h1>Listing menu_item_ingredients</h1>

<table>
  <tr>
    <th>Menu item</th>
    <th>Ingredient</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menu_item_ingredients.each do |menu_item_ingredient| %>
  <tr>
    <td><%= menu_item_ingredient.menu_item_id %></td>
    <td><%= menu_item_ingredient.ingredient_id %></td>
    <td><%= menu_item_ingredient.user_id %></td>
    <td><%= link_to 'Show', menu_item_ingredient %></td>
    <td><%= link_to 'Edit', edit_menu_item_ingredient_path(menu_item_ingredient) %></td>
    <td><%= link_to 'Destroy', menu_item_ingredient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu item ingredient', new_menu_item_ingredient_path %>

app/views/menu_item_ingredients/new.html.erb
<h1>New menu_item_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_item_ingredients_path %>

app/views/menu_item_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Menu item:</b>
  <%= @menu_item_ingredient.menu_item_id %>
</p>

<p>
  <b>Ingredient:</b>
  <%= @menu_item_ingredient.ingredient_id %>
</p>

<p>
  <b>User:</b>
  <%= @menu_item_ingredient.user_id %>
</p>


<%= link_to 'Edit', edit_menu_item_ingredient_path(@menu_item_ingredient) %> |
<%= link_to 'Back', menu_item_ingredients_path %>